M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu22.04.1} date Tue Jan 24 12:47:53 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-24T12:47:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X127.762Y-75.946
X127.762Y-93.218
T0
M30
